export const SUGGEST_PRODUCTS = "SUGGEST_PRODUCTS";
export const SHOW_LOADING = "SHOW_LOADING";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SHOW_PRODUCT_CATEGORIES = "SHOW_PRODUCT_CATEGORIES";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const GET_PRODUCT_CATEGORIES = "GET_PRODUCT_CATEGORIES";
